apiVersion: apps/v1
kind: Deployment
metadata:
  name: realisasi-ui
  labels:
    app: realisasi-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realisasi-ui
  template:
    metadata:
      labels:
        app: realisasi-ui
    spec:
      containers:
        - name: realisasi-ui
          image: realisasi-ui:dev
          imagePullPolicy: Never
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
