apiVersion: v1
kind: Service
metadata:
  name: realisasi-ui
  labels:
    app: realisasi-ui
spec:
  type: ClusterIP
  selector:
    app: realisasi-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
